#!/bin/bash

# CONFIG: MAIL PREFERENCES
EMAIL="${USER}@${HOSTNAME}"	# Where to send mail notifications

# CONFIG: WARNING LEVELS
WARNING_TEMP[1]=50		# CPU temperature warning in degrees celcius
WARNING_TEMP[0]=70		# CPU temperature danger level in degrees celcius
WARNING_DISK_SPACE=5000	# remaining disk space warning in MB
WARNING_FREE_RAM=5	# remaining RAM warning in percentage

# CONFIG: PULSE METHODS
ENABLE_LED_NOTIFICATION=1	# Enable visual notifications via LEDs
ENABLE_BUZZER_NOTIFICATION=1	# Enable audible notifications via buzzers

# CONFIG: PULSE NUMBERS	# Number of times to flash the LED, 0 to disable
WARNING_TEMP_PULSE=1
WARNING_DISK_PULSE=1
WARNING_RAM_PULSE=1
WARNING_NETWORK_PULSE=1
WARNING_INTERNET_PULSE=1

# CONFIG: GPIO PINS
LED_PIN=( 7 )	# the GPIO numbers corresponding to the pins with LEDS
BUZZER_PIN=( )	# the GPIO numbers corresponding to the pins with buzzers

# CONFIG: TIMINGS
SLEEP_TIME=1	# time to wait between health check cycles

# CONFIG: LED RATES
LED_ON_TIME=1	# time to keep the LED on in seconds (float)
LED_OFF_TIME=1	# time between LED flashes

# CONFIG: BUZZ RATES
BUZZER_ON_TIME=1	# time the speaker buzzes for
BUZZER_OFF_TIME=1	# time between buzzes

# CONFIG: LOGGING
LOG_FILE="/home/pi/bin/log.notifier"	# log location; change to "/dev/null" to disable
TAG_WARNING[1]="[ WARNING ]"	# tag for normal warnings in logs
TAG_WARNING[0]="[ DANGER ]"	# tag for danger warnings in logs

# CONSTANTS: DIRECTORIES
TEMP_FILE='/sys/class/thermal/thermal_zone0/temp'	# file that contains the CPU temperature
GPIO_ROOT='/sys/class/gpio'	# root directory for GPIO operations
GPIO_EXPORT="${GPIO_ROOT}/export"	# GPIO export path

# CONSTANTS: GPIO VALUES
ON=1	# ON constant
OFF=0	# OFF constant

# VERSION
VERSION='Notifier v0.1'

# USAGE
USAGE='Usage: notifier [OPTIONS]
	--check-disk		Check for low free disk space.
				Override global setting in config.
	--no-check-disk		Do not check for low free disk space.
				Override global setting in config.
	--check-internet	Check for an Internet connection.
				Override global setting in config.
	--no-check-internet	Do not check for an Internet connection.
				Override global setting in config.
	--check-network		Check for a network connection.
				Override global setting in config.
	--no-check-internet	Do not check for a network connection.
				Override global setting in config.
	--check-ram		Check for low free free RAM.
				Override global setting in config.
	--no-check-ram		Do not check for low free free RAM.
				Override global setting in config.
	--check-temp		Check for high CPU temperature.
				Override global setting in config.
	--no-check-temp		Do not check for high CPU temperature.
				Override global setting in config.
	--enable-buzzer		Enable notifications via buzzers/speakers.
				Override global setting in config.
	--disable-buzzer	Disable notifications via buzzers/speakers.
				Override global setting in config.
	--enable-led		Enable notifications via LEDs.
				Override global setting in config.
	--disable-led		Disable notifications via LEDs.
				Override global setting in config.
	-h, --help		Show this help.
	-m, --mail		Mail log messages to default address set as $EMAIL.
	-s, --standalone	Run as a standalone script.
	-v, --verbose		Print verbose messages.
	-V, --version		Print version information and exit.
'

# Initialize all needed GPIO pins
function init_gpio() {
	if [ $ENABLE_LED_NOTIFICATION ]; then
		init_led_gpio
	fi

	if [ $ENABLE_BUZZER_NOTIFICATION ]; then
		init_buzzer_gpio
	fi
}

# Initialize the GPIO(s) for LEDs if needed
function init_led_gpio()
{
	for pin in ${LED_PIN[@]}
	do
		# Check if the pin's GPIO directory already exists, otherwise export it
		if [ ! -d "${GPIO_ROOT}/gpio${pin}" ]; then
			if [ $verbose ]; then
				echo "Exporting pin #$pin"
			fi

			echo $pin > $GPIO_EXPORT
			echo "out" > "${GPIO_ROOT}/gpio${pin}/direction"
		fi
	done
}

function init_buzzer_gpio()
{
	for pin in ${BUZZER_PIN[@]}
	do
		# Check if the pin's GPIO directory already exists, otherwise export it
		if [ ! -d "${GPIO_ROOT}/gpio${pin}" ]; then
			if [ $verbose ]; then
				echo "Exporting pin #$pin"
			fi

			echo $pin > $GPIO_EXPORT
			echo "out" > "${GPIO_ROOT}/gpio${pin}/direction"
		fi
	done
}


# Write a value to a GPIO pin
# $1 	Pin to write value to.
# $2 	Value to output to pin.
function gpio_out() {
	if [ $verbose ]; then
		echo "Writing $2 to pin #$1"
	fi

	echo $2 > "${GPIO_ROOT}/gpio${1}/value"
}

# Notify the user via current configuration of methods.
# $1	Number of notifications.
# $2	Log message.
function notify() {
	if  (( $1 > 0 )); then
		pulse $1
	fi

	if [ "$2" ]; then
		log $2
	fi
}

# Send a visual or audible pulse according to the current configuration.
# $1	Number of pulses.
function pulse() {
	if (( $1 > 0 )); then
		if [ $ENABLE_LED_NOTIFICATION ]; then
			flash_led $1
		fi

		if [ $ENABLE_BUZZER_NOTIFICATION ]; then
			buzz_speaker $1
		fi
	fi
}

# Flash the LED on $led_pin
# $1 	Number of times to flash the LED.
# $2 	Optional. Log message.
function flash_led() {
	init_led_gpio	# about to use GPIO, initialize if needed

	if [ $verbose ]; then
		echo "Flash LED $1x: $2"
	fi

	for (( i=1; i <= $1; i++ ))
	do
		for pin in ${LED_PIN[@]}
		do
			# Flash the LED for 0.15 seconds
			gpio_out $pin $ON
			sleep $LED_ON_TIME
			gpio_out $pin $OFF
			sleep $LED_OFF_TIME
		done
	done

	# TODO, remove this when all direct calls from check functions have been removed
	if [ "$2" ]; then
		log $2
	fi

}

# Pulse an audible notification through a speaker.
# $1	Number of buzzes to play.
function buzz_speaker() {
	init_buzzer_gpio	# about to use GPIO, initialize if needed

	if [ $verbose ]; then
		echo "Buzz speaker $1x"
	fi

	for (( i=1; i <= $1; i++ ))
	do
		for pin in ${BUZZER_PIN[@]}
		do
			# Buzz the speaker
			gpio_out $pin $ON
			sleep $BUZZER_ON_TIME
			gpio_out $pin $OFF
			sleep $BUZZER_OFF_TIME
		done
	done

}

function check_levels() {
	if [ $verbose ]; then
		echo "Checking levels"
	fi

	if [ $WARNING_TEMP_PULSE -gt 0 ]; then
		check_temp
	fi

	if [ $WARNING_DISK_PULSE -gt 0 ]; then
		check_disk
	fi

	if [ $WARNING_RAM_PULSE -gt 0 ]; then
		check_ram
	fi

	if [ $WARNING_NETWORK_PULSE -gt 0 ]; then
		check_network
	fi

	if [ $WARNING_INTERNET_PULSE -gt 0 ]; then
		check_internet
	fi

	send_log	# mail the log
	log=''	# clear the log
}

function check_temp() {
	if [ $verbose ]; then
		echo "Checking CPU temperature"
	fi

	temp=`cat $TEMP_FILE`
	warning_temp=$[ WARNING_TEMP[1]*1000 ]

	if [ $temp -gt $warning_temp ];	then
		flash_led $WARNING_TEMP_PULSE "${TAG_WARNING[1]} CPU temperature: $(awk -v t=$temp 'BEGIN { print (t / 1000) }') oC"
	fi
}

function check_disk() {
	if [ $verbose ]; then
		echo "Checking disk space"
	fi

	# get current disk space
	disk_space=`df -m | grep rootfs | awk '{ print $4 }'`

	# flash the LED if the disk space is below the warning level
	if [ $disk_space -lt $WARNING_DISK_SPACE ]; then
		flash_led $WARNING_DISK_PULSE "${TAG_WARNING[1]} Free disk space: $disk_space"
	fi
}

# Get free RAM percentage
function check_ram() {
	if [ $verbose ]; then
		echo "Checking RAM"
	fi

	# get memory usage
	total_mem=`free -ot | awk ' END { print $2 } '`
	free_mem=`free -ot | awk ' END { print $4 } '`

	# calculate memory usage in percentages
	free_ram=$(awk -v f=$free_mem -v t=$total_mem 'BEGIN { print (f / t * 100) }')

	if [ ${free_ram/.*} -le $WARNING_FREE_RAM ]; then
		flash_led $WARNING_RAM_PULSE "${TAG_WARNING[1]} RAM Remaining: ${free_ram}%"
	fi
}

# Check for a network connection
function check_network() {
	if [ $verbose ]; then
		echo "Checking network connection"
	fi

	# check if system has any IP other than the loopback IP
	if ! ip addr | grep inet | grep -v "127.0.0.1" > /dev/null; then
		flash_led $WARNING_NETWORK_PULSE "${TAG_WARNING[1]} No network connection"
	fi
}

# Check for an Internet connection
function check_internet() {
	if [ $verbose ]; then
		echo "Checking Internet Connection"
	fi

	if ! ping -c 1 google.com > /dev/null; then
		flash_led 1 "${TAG_WARNING[1]} No Internet connection."
	fi
}

function log() {
	msg="`date`\t$1"
	echo -e $msg >> $LOG_FILE
	log="${log}$msg\n"
}

# Mail the log in $log and clear it
function send_log() {
	# if the log isn't empty and the mail option is on
	if [ [ $log ] && [ $mail ] ]; then
		if [ $verbose ]; then
			echo "Mail warning"
		fi

		echo -e $message | mail -s "`hostname` Warning" $EMAIL
	fi
}

# Initialize the GPIO and prepare variables
function init() {
	if [ $verbose ]; then
		echo "Initializing"
	fi

	load_config
	init_gpio
}

# Load any available configuration files.
function load_config() {
	# Load configuration file from /etc/notifier.cfg, if it's readable
	if [ -r /etc/notifier.cfg ]; then
		source /etc/notifier.cfg
	fi

	# Load configuration file from ~/.notifier, if it's readable
	if [ -r ~/.notifier ]; then
		source ~/.notifier
	fi
}

if [ $verbose ]; then
	echo "Checking options"
fi

while [ $# -gt 0 ]
do
	case $1 in
		--check-disk)
			# override global setting for check for disk space
			$WARNING_DISK_PULSE=1
			;;
		--no-check-disk)
			# override global setting for check for disk space
			$WARNING_DISK_PULSE=0
			;;
		--check-internet)
			# override global setting for check for Internet connection
			$WARNING_INTERNET_PULSE=1
			;;
		--no-check-internet)
			# override global setting for check for Internet connection
			$WARNING_INTERNET_PULSE=0
			;;
		--check-network)
			# override global setting for check for network connection
			$WARNING_NETWORK_PULSE=1
			;;
		--no-check-network)
			# override global setting for check for network connection
			$WARNING_NETWORK_PULSE=0
			;;
		--check-ram)
			# override global setting for check for free RAM
			$WARNING_RAM_PULSE=1
			;;
		--no-check-ram)
			# override global setting for check for free RAM
			$WARNING_RAM_PULSE=0
			;;
		--check-temp)
			# override global setting for check for CPU temperature
			$WARNING_TEMP_PULSE=1
			;;
		--no-check-temp)
			# override global setting for check for CPU temperature
			$WARNING_TEMP_PULSE=0
			;;
		--enable-led)
			# override the config setting for LED notifications
			$ENABLE_LED_NOTIFICATION=1
			;;
		--disable-led)
			# override the config setting for LED notifications
			$ENABLE_LED_NOTIFICATION=0
			;;
		--enable-buzzer)
			# override the config setting for buzzer notifications
			$ENABLE_BUZZER_NOTIFICATION=1
			;;
		--disable-buzzer)
			# override the config setting for buzzer notifications
			$ENABLE_BUZZER_NOTIFICATION=0
			;;
		-m|--mail)
			# mail log messages
			$mail=1
			;;
		-h|--help)
			# print usage and exit
			echo "$USAGE"
			exit 0;
			;;
		-s|--standalone)
			# run as standalone; run in infinite loop
			loop=1
			;;
		-v|--verbose)
			verbose=1
			;;
		-V|--version)
			# print version and exit
			echo "$VERSION"
			exit 0
			;;
		*)
			# unknown option; exit
			echo "Unknown argument: $1"
			echo "$USAGE"
			exit 1
			;;
	esac
	shift
done

if [ $verbose ]; then
	echo "Done."
fi

if [ $loop ]; then
	# run script in an infinite loop
	while true;
	do
		check_levels
		# sleep for 1 second
		sleep $SLEEP_TIME
	done
else
	check_levels
fi

exit 0;
